# Complementaria semana 6

In [1]:
#Importar las librerías
import numpy as np
from jmarkov.ctmc import ctmc

In [2]:
#Tasas a utilizar
tasa_ambiente_alto = 0.1
tasa_ambiente_bajo = 0.2
tasa_corrosion_alto_bajo = 0.3
tasa_corrosion_bajo_alto = 0.4

### Vector de estados

In [3]:
# S_X = {1, 2, 3, 4, 5}
estados_corrosion = [i for i in range(1,6)]
estados_corrosion

[1, 2, 3, 4, 5]

In [4]:
# S_Y = {'Alto', 'Bajo'}
estados_ambiente = ['Alto', 'Bajo']
estados_ambiente

['Alto', 'Bajo']

In [5]:
# S_Z = S_X x S_Y (todas las combinaciones posibles)
estados = []
for i in estados_corrosion:
    for j in estados_ambiente:
        estado = ",".join((str(i),str(j))) # Une dos elementos como strings separados por una coma
        estados.append(estado) # Lo agrega a la lista de estados

estados = np.array(estados)
estados

array(['1,Alto', '1,Bajo', '2,Alto', '2,Bajo', '3,Alto', '3,Bajo',
       '4,Alto', '4,Bajo', '5,Alto', '5,Bajo'], dtype='<U6')

### Matriz de ceros

In [6]:
#Crear una matriz de ceros
matrizQ = np.zeros((len(estados),len(estados)))
matrizQ

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Explicación uso `enumerate`

In [7]:
# Recorrido de los estados con enumerate para obtener el índice (posición) y el valor (estado_inicial (i,j)) de cada estado.
for indice, estado_inicial in enumerate(estados):
    print(indice, "->", estado_inicial)

0 -> 1,Alto
1 -> 1,Bajo
2 -> 2,Alto
3 -> 2,Bajo
4 -> 3,Alto
5 -> 3,Bajo
6 -> 4,Alto
7 -> 4,Bajo
8 -> 5,Alto
9 -> 5,Bajo


### Explicación uso `split`

In [8]:
# Usar split para obtener i y j (niveles de corrosión y ambiente) del estado inicial (i,j)
for indice, estado_inicial in enumerate(estados):
    i = int(estado_inicial.split(",")[0])
    j = estado_inicial.split(",")[1]
    print(indice, "->", estado_inicial, "->", i, j)


0 -> 1,Alto -> 1 Alto
1 -> 1,Bajo -> 1 Bajo
2 -> 2,Alto -> 2 Alto
3 -> 2,Bajo -> 2 Bajo
4 -> 3,Alto -> 3 Alto
5 -> 3,Bajo -> 3 Bajo
6 -> 4,Alto -> 4 Alto
7 -> 4,Bajo -> 4 Bajo
8 -> 5,Alto -> 5 Alto
9 -> 5,Bajo -> 5 Bajo


### Llenar la matriz de transición

In [9]:
for fila, estado_inicial in enumerate(estados): # El índice del estado inicial es la fila

    # Estado inicial: (i,j)
    i = int(estado_inicial.split(",")[0])
    j = estado_inicial.split(",")[1]

    for columna, estado_futuro in enumerate(estados): # El índice del estado futuro es la columna
        
        # Estado futuro: (i',j')
        i_ = int(estado_futuro.split(",")[0])
        j_ = estado_futuro.split(",")[1]

        if i_==i+1 and j_==j and i<5:
            matrizQ[fila,columna] = tasa_ambiente_alto
        elif i_==i-1 and j_==j and i>1:
            matrizQ[fila,columna] = tasa_ambiente_bajo
        elif i_==i and j=="Alto" and j_=="Bajo":
            matrizQ[fila,columna] = tasa_corrosion_alto_bajo
        elif i_ ==i and j=="Bajo" and j_=="Alto":
            matrizQ[fila,columna] = tasa_corrosion_bajo_alto

# Llenamos la diagonal
for fila, estado_inicial in enumerate(estados):
    matrizQ[fila,fila] = -sum(matrizQ[fila,:])

matrizQ

array([[-0.4,  0.3,  0.1,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.4, -0.5,  0. ,  0.1,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.2,  0. , -0.6,  0.3,  0.1,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.2,  0.4, -0.7,  0. ,  0.1,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.2,  0. , -0.6,  0.3,  0.1,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0.2,  0.4, -0.7,  0. ,  0.1,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.2,  0. , -0.6,  0.3,  0.1,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0.2,  0.4, -0.7,  0. ,  0.1],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.2,  0. , -0.5,  0.3],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.2,  0.4, -0.6]])

In [10]:
# Verificar que las filas sumen cero
np.sum(matrizQ, axis=1)

# Puede pasar que no sean exactamente cero, pero deben ser muy cercanas a cero

array([-2.77555756e-17,  2.77555756e-17,  2.77555756e-17, -2.77555756e-17,
        2.77555756e-17, -2.77555756e-17,  2.77555756e-17, -2.77555756e-17,
        0.00000000e+00,  0.00000000e+00])

### Crear objeto CMTC

In [11]:
# Creamos el objeto cadena
cadena = ctmc(matrizQ)

### Pregunta 1: análisis transitorio (probabilidad)

In [12]:
# Definir la distribución inicial
alpha = np.zeros(len(estados))
alpha[np.where(estados== "1,Alto")]=0.5
alpha[np.where(estados== "1,Bajo")]=0.5

# Analizar las probabilidades de estado transitorio
probs_transitorio = cadena.transient_probabilities(24*7, alpha)
estado_interes1 = np.where(estados== "5,Alto")
estado_interes2 = np.where(estados== "5,Bajo")

# Calcular la probabilidad de interés
prob_interes = probs_transitorio[estado_interes1]+probs_transitorio[estado_interes2]
prob_interes

array([0.03225762])

### Pregunta 2: tiempo de ocupación

In [13]:
#Calcular el tiempo de ocupación
tiempo_ocupacion = cadena.occupation_time(2*7*24)
tiempo_interes = 0
estado_inicial = np.where(estados == "3,Alto")

# Calcular el tiempo de ocupación para estados de interés
for columna, estado_futuro in enumerate(estados):
    i_ = int(estado_futuro.split(",")[0])
    j_ = estado_futuro.split(",")[1]
    if i_>=4:
        tiempo_interes += tiempo_ocupacion[estado_inicial, columna][0][0] # El [0][0] es para obtener solamente el valor numérico del array que devuelve la función

tiempo_interes

np.float64(34.4620179949542)

### Pregunta 3: tiempo de primera pasada

In [14]:
# Calcular el tiempo de primera pasada

# Estados de interés
estado_inicial = np.where(estados=='2,Bajo')
estado_futuro = np.where(estados == '5,Alto')

# Calcular el tiempo
cadena.first_passage_time(estado_futuro)[estado_inicial][0][0]  # El [0][0] es para obtener solamente el valor numérico del array que devuelve la función


np.float64(276.4706507868981)

In [15]:
# Sin el [0][0] la función devuelve un array, por lo que se ve así:
cadena.first_passage_time(estado_futuro)[estado_inicial] 

array([[276.47065079]])