In [ ]:
import numpy as np
from jmarkov.dtmc import dtmc

In [7]:
filas = 5
columnas = 5
matriz = np.zeros((filas, columnas), dtype=float)

# Recorrer filas
for i in range(filas):
    # Recorrer columnas
    for j in range(columnas):
        
        if j == i + 1 and i < 4:
            matriz[i][j] = 0.5
            
        elif j == i - 1 and i > 0:
            matriz[i][j] = 0.2
            
        elif j == i and 0 < i < 4:
            matriz[i][j] = 0.3
            
        elif j == i == 0:
            matriz[i][j] = 0.5
            
        elif j == i == 4:
            matriz[i][j] = 0.8
            
        else:
            matriz[i][j] = 0
            
print(matriz)

[[0.5 0.5 0.  0.  0. ]
 [0.2 0.3 0.5 0.  0. ]
 [0.  0.2 0.3 0.5 0. ]
 [0.  0.  0.2 0.3 0.5]
 [0.  0.  0.  0.2 0.8]]


In [13]:
P = dtmc(matriz)

In [14]:
alpha = np.zeros(5)
alpha[1] = 1.0
alpha

array([0., 1., 0., 0., 0.])

In [19]:
probabilidades_viernes = P.transient_probabilities(n=4,alpha=alpha)
probabilidades_finales = probabilidades_viernes[-1] + probabilidades_viernes[-2]
probabilidades_finales

0.4475

In [21]:
probabilidades_martes = P.transient_probabilities(n=1,alpha=alpha)
probabilidades_miercoles = P.transient_probabilities(n=2,alpha=alpha)
probabilidades_jueves = P.transient_probabilities(n=3,alpha=alpha)
probabilidades_viernes = P.transient_probabilities(n=4,alpha=alpha)

In [23]:
gasto = 120
gasto_total = (probabilidades_martes[4] * gasto) + (probabilidades_miercoles[4] * gasto) + (probabilidades_jueves[4] * gasto) + (probabilidades_viernes[4] * gasto)
gasto_total

40.5