## Problema 1: Héroes y villanos

In [26]:
# importaciones necesarias
from jmarkov.mdp.dtmdp import dtmdp
import numpy as np

In [27]:
# definir estados
estados = np.array(["Ataque Centro", "Ataque Suburbio"])

# definir acciones
acciones = np.array(["Ir a Centro", "Ir a Suburbio"])


# definir diccionario de matrices (cada matriz asociada a su acción correspondiente)
matriz_ir_centro = np.array([[0.3, 0.7], 
                            [0.8, 0.2]])
matriz_ir_sub = np.array([[0.5, 0.5], 
                          [0.6, 0.4]])

matrices = {}

matrices["Ir a Centro"] = matriz_ir_centro
matrices["Ir a Suburbio"] = matriz_ir_sub

# derinir retornos: filas -> estados y columnas -> acciones
retornos = np.array([[0.3, 0.5],
                     [0.8, 0.4]])

# definir un factor de descuento
beta = 0.9

# Creamos el objeto mdp con la librería jmarkov
mdp_heroes = dtmdp(estados, acciones, matrices, retornos, beta)


In [28]:
# Resolver el mdp con el método .solve(): esto nos devuelve el valor esperado al seguir la política óptima en cada estado, y la política óptima para cada estado
value_functions, optimal_policy = mdp_heroes.solve(0, minimize=False, method="policy_iteration") # "value_iteration"


In [29]:
value_functions

array([6.06299207, 6.29921255])

In [30]:
optimal_policy

{np.str_('Ataque Centro'): np.str_('Ir a Suburbio'),
 np.str_('Ataque Suburbio'): np.str_('Ir a Centro')}

In [31]:
# Calcular el valor esperado de la política óptima (en total)
mdp_heroes.expected_policy_value(value_functions, optimal_policy)

np.float64(6.153846100216111)

In [ ]:
# Obtener la matriz de transición de la política óptima
mdp_heroes.policy_transition_matrix(optimal_policy)

array([[0.5, 0.5],
       [0.8, 0.2]])

## Problema 2: Los estudiantes de Los Alpes

In [33]:
P_1 = np.array([[1,0,0,0],
                [0.05,0.7,0.15,0.1],
                [0,0.2,0.5,0.3],
                [0,0,0.1,0.9]])

P_2 = np.array([[0.6,0.4,0,0],
                [0.25,0.6,0.1,0.05],
                [0.1,0.3,0.5,0.1],
                [0,0.05,0.25,0.7]])

P_3 = np.array([[0.9,0.1,0,0],
                [0.5,0.5,0,0],
                [0.2,0.3,0.5,0],
                [0,0,1,0]])

Completar todos los pasos, como el problema 1:

In [40]:
beta = 0.9

estados = np.array(['E', 'B', 'P', 'R'])

acciones = np.array([i for i in range(1,4)])

retornos = np.array([[-1000, 3, 0],
                    [4, 2, -10],
                    [3, -5, -10],
                    [-3, -15, -1000]])
matrices = {}
matrices[1] = P_1
matrices[2] = P_2
matrices[3] = P_3
matrices

{1: array([[1.  , 0.  , 0.  , 0.  ],
        [0.05, 0.7 , 0.15, 0.1 ],
        [0.  , 0.2 , 0.5 , 0.3 ],
        [0.  , 0.  , 0.1 , 0.9 ]]),
 2: array([[0.6 , 0.4 , 0.  , 0.  ],
        [0.25, 0.6 , 0.1 , 0.05],
        [0.1 , 0.3 , 0.5 , 0.1 ],
        [0.  , 0.05, 0.25, 0.7 ]]),
 3: array([[0.9, 0.1, 0. , 0. ],
        [0.5, 0.5, 0. , 0. ],
        [0.2, 0.3, 0.5, 0. ],
        [0. , 0. , 1. , 0. ]])}

In [41]:
mdp_estudiantes = dtmdp(estados, acciones, matrices, retornos, beta)

In [42]:
# Resolver el mdp con el método .solve(): esto nos devuelve el valor esperado al seguir la política óptima en cada estado, y la política óptima para cada estado
value_functions, optimal_policy = mdp_estudiantes.solve(0, minimize=False, method="policy_iteration") # "value_iteration"


In [43]:
value_functions

array([ 14.54413104,  10.25083408,   1.37878465, -15.13636513])

In [44]:
optimal_policy

{np.str_('E'): np.int64(2),
 np.str_('B'): np.int64(2),
 np.str_('P'): np.int64(1),
 np.str_('R'): np.int64(1)}

In [46]:
mdp_estudiantes.expected_policy_value(value_functions, optimal_policy)

np.float64(-4.146341393645345)

In [45]:
mdp_estudiantes.policy_transition_matrix(optimal_policy)

array([[0.6 , 0.4 , 0.  , 0.  ],
       [0.25, 0.6 , 0.1 , 0.05],
       [0.  , 0.2 , 0.5 , 0.3 ],
       [0.  , 0.  , 0.1 , 0.9 ]])