## Gadgets-R-Us
***
### Enunciado

Las acciones comunes de la compañía *Gadgets-R-Us* se negocian en el mercado de valores. El director financiero de *Gadgets-R-Us* compra y vende la acción de tal manera que el precio nunca cae por debajo de $2 y nunca sube por encima de $10.

Análisis estadísticos sugieren que los potenciales movimientos en el precio de la acción $I_n$ forman una secuencia de variables aleatorias i.i.d. con la siguiente distribución de probabilidad:

$$P(I_n = k) = 0.2, \quad k = -2,-1,0,1,2.$$

Sea $X_n$ el precio de la acción al final del día $n$.
El espacio de estados es:
$$[S_x = {2,3,\dots,9,10}.]$$


Suponga que el Sr. Jones compra la acción cuando está cotizando a **$5** y decide venderla tan pronto como se negocie a **$8 o más**.

La matriz de transición $P$ es:
$$P =
\begin{bmatrix}
0.6 & 0.2 & 0.2 & 0   & 0   & 0   & 0   & 0   & 0   \\
0.4 & 0.2 & 0.2 & 0.2 & 0   & 0   & 0   & 0   & 0   \\
0   & 0.2 & 0.2 & 0.2 & 0.2 & 0   & 0   & 0   & 0   \\
0   & 0   & 0.2 & 0.2 & 0.2 & 0.2 & 0   & 0   & 0   \\
0   & 0   & 0   & 0.2 & 0.2 & 0.2 & 0.2 & 0   & 0   \\
0   & 0   & 0   & 0   & 0.2 & 0.2 & 0.2 & 0.2 & 0   \\
0   & 0   & 0   & 0   & 0   & 0.2 & 0.2 & 0.2 & 0.2 \\
0   & 0   & 0   & 0   & 0   & 0   & 0.2 & 0.2 & 0.4 \\
0   & 0   & 0   & 0   & 0   & 0   & 0   & 0.2 & 0.6 
\end{bmatrix}$$


#### ¿Cuál es la cantidad de tiempo esperada que el Sr. Jones terminará teniendo la acción?

In [3]:
import numpy as np
# Declarar la matriz Q y la matriz identidad 

Q = np.array([
    [3/5, 1/5, 1/5, 0,   0,   0  ],
    [2/5, 1/5, 1/5, 1/5, 0,   0  ],
    [0,   1/5, 1/5, 1/5, 1/5, 0  ],
    [0,   0,   1/5, 1/5, 1/5, 1/5],
    [0,   0,   0,   1/5, 1/5, 1/5],
    [0,   0,   0,   0,   1/5, 1/5]
])

# Matriz identidad del mismo tamaño que Q
I = np.eye(Q.shape[0])

# Calcular (I - Q)
I_minus_Q = I - Q

# Calcular la inversa de (I - Q)
N = np.linalg.inv(I_minus_Q)

print("Matriz N (I - Q)^-1:")
print(N)

# Sumar la fila i = 5, para sacar el tiempo total esperado hasta que venda la accion empezando en el estado 5
tiempo_total_esperado = np.sum(N[5, :])
print(f"\nTiempo total esperado hasta que venda la acción empezando en el estado 5: {tiempo_total_esperado} días")

Matriz N (I - Q)^-1:
[[3.83891213 1.33891213 1.5167364  0.88912134 0.70083682 0.39748954]
 [2.10251046 2.10251046 1.30753138 1.0251046  0.69037657 0.42887029]
 [0.57531381 0.57531381 1.72594142 0.75313808 0.71129707 0.36610879]
 [0.15690377 0.15690377 0.4707113  1.56903766 0.64853556 0.55439331]
 [0.041841   0.041841   0.12552301 0.41841004 1.50627615 0.48117155]
 [0.01046025 0.01046025 0.03138075 0.10460251 0.37656904 1.37029289]]

Tiempo total esperado hasta que venda la acción empezando en el estado 5: 1.9037656903765687 días
